function sh = loadShipTrack(latitude, longitude)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: O:\arcsat\svn\trunk\matlab_code\ships\2300001.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/03/03 09:46:53

%% Import the data
%sh = xlsread('O:\arcsat\svn\trunk\matlab_code\ships\209729000.xlsx','Sheet1');
sh = xlsread('ships/209506000.xlsx','Sheet1');

%% Clear temporary variables
clearvars raw;

numInTrack = size(sh,1);
trackPoints = zeros(numInTrack,2);
prevX = 0;
prevY = 0;
j=1;
for i=1:numInTrack
    [X, Y] = calcXY(latitude,longitude,sh(i,1),sh(i,2));
    if (X~=prevX || Y~=prevY)
        trackPoints(j,:) = [X, Y];
        j=j+1;
        prevX = X;
        prevY = Y;
    end

end
trackPoints = trackPoints(1:j-1,:);
plot(trackPoints(:,1),trackPoints(:,2),'y*-');
end